name: OakRewind
version: '${version}'
main: dev.oakheart.oakrewind.OakRewind
description: 'Rewind explosions with beautiful rebuilding animations.'
api-version: '1.21.10'
authors:
  - Loralon
website: https://github.com/LoralonMC/OakRewind
permissions:
  oakrewind.*:
    description: 'Grants all OakRewind permissions'
    default: op
    children:
      oakrewind.reload: true
  oakrewind.reload:
    description: 'Allows reloading of the OakRewind configuration.'
    default: op
